version: 2
# enable-beta-ecosystems: true
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
    labels:
      - "github-actions"
      - "dependencies"

  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "/code/terraform"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
    labels:
      - "terraform"
      - "dependencies"

  # Maintain dependencies for Terraform with ARM
  - package-ecosystem: "terraform"
    directory: "/code/workaroundWithArm"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
    labels:
      - "terraform"
      - "dependencies"

  # Maintain dependencies for Terraform Use-Case
  - package-ecosystem: "terraform"
    directory: "/code/use-case"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
    labels:
      - "terraform"
      - "dependencies"

  # Maintain dependencies for Terraform Use-Case
  - package-ecosystem: "terraform"
    directory: "/code/use-case-logic"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
    labels:
      - "terraform"
      - "dependencies"

  # Maintain dependencies for Terraform pythonFunction
  - package-ecosystem: "terraform"
    directory: "/code/pythonFunction"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "10:00"
    labels:
      - "terraform"
      - "dependencies"
