name: Terraform Testing
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/pythonFunction/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "code/pythonFunction/**"

jobs:
  terraform_lint:
    uses: ./.github/workflows/_terraformLintTemplate.yml
    name: "Terraform Lint"
    with:
      terraform_version: "1.3.8"
      working_directory: "./code/pythonFunction"
